[window]
padding = { x = 2, y = 2 }
option_as_alt = 'Both'

[font]
size = 9.5

[font.bold]
# family = "JetBrainsMono Nerd Font"

[font.bold_italic]
# family = "JetBrainsMono Nerd Font"

[font.italic]
# family = "JetBrainsMono Nerd Font"

[font.normal]
# family = "JetBrainsMono Nerd Font"
