[window]
padding = { x = 10, y = 10 }


[font]
size = 11.0

[font.bold]
family = "CascadiaCode Nerd Font"
# style = "Bold"

[font.bold_italic]
family = "CascadiaCode Nerd Font"
# style = "Bold Italic"

[font.italic]
family = "CascadiaCode Nerd Font"
# style = "Italic"

[font.normal]
family = "CascadiaCode Nerd Font"
# style = "Regular"
